# Generated by Django 2.1.5 on 2019-02-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_reason', models.CharField(max_length=128)),
                ('leave_date', models.DateField(blank=True, default=0)),
                ('leave_time', models.CharField(default=0, max_length=128)),
                ('leave_status', models.CharField(default=0, max_length=128)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
            ],
            options={
                'verbose_name_plural': 'Leave',
            },
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Manager',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('project_technology', models.CharField(max_length=128)),
                ('project_status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=128)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=128)),
                ('last_name', models.CharField(default='', max_length=128)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(default='', max_length=128, unique=True)),
                ('password', models.CharField(default='', max_length=50, unique=True)),
                ('phone_no', models.CharField(max_length=128, unique=True)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('qualification', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('skills', models.CharField(max_length=128)),
                ('experience', models.IntegerField()),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images')),
                ('salary', models.IntegerField(default=0)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.staff'),
        ),
        migrations.AddField(
            model_name='manager',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.staff'),
        ),
        migrations.AddField(
            model_name='leave',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.staff'),
        ),
        migrations.AddField(
            model_name='employee',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.staff'),
        ),
    ]
