# Generated by Django 2.1.5 on 2019-02-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20190226_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_assingment',
            options={'verbose_name_plural': 'Assigned Projects'},
        ),
    ]
