# Generated by Django 2.1.5 on 2019-02-27 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20190226_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_assingment',
            old_name='pip',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='project_assingment',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='project_assingment',
            name='staff',
        ),
        migrations.AddField(
            model_name='project',
            name='dept',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
        migrations.AddField(
            model_name='project_assingment',
            name='emp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
