# Generated by Django 2.1.7 on 2019-03-05 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_project_assingment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=128)),
                ('time', models.CharField(max_length=128)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project_assingment')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.staff')),
            ],
            options={
                'verbose_name_plural': 'Project Inquiry',
            },
        ),
    ]
