# Generated by Django 2.1.5 on 2019-03-08 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20190306_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_inquiry',
            name='reply',
            field=models.CharField(blank=True, default='no', max_length=128),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='project_inquiry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project_assingment'),
        ),
    ]
