# Generated by Django 2.1.5 on 2019-03-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20190308_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_assingment',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('inprogress', 'Inprogress'), ('incomplete', 'Incomplete')], default='incomplete', max_length=128),
        ),
    ]
