# Generated by Django 2.1.5 on 2019-03-14 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20190308_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_date_one',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
