# Generated by Django 2.1.5 on 2019-03-14 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20190314_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_date_one',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
