# Generated by Django 2.1.5 on 2019-03-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20190314_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_sheet',
            name='pid',
            field=models.ForeignKey(default='project_assignment', on_delete=models.Model, to='employee.project'),
        ),
    ]
